version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: api-billar
      MYSQL_USER: root
      MYSQL_PASSWORD: 3012149365
      MYSQL_ROOT_PASSWORD: 3012149365
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: api-billar
      DB_USERNAME: root
      DB_PASSWORD: 3012149365

volumes:
  mysql_data:

# Servicio independiente para ejecutar las migraciones
migrate:
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app
  depends_on:
    - app
  entrypoint: ["php", "artisan", "migrate"]
